
CREATE TABLE TEN (
  IDETEN int(3) NOT NULL AUTO_INCREMENT,
  NOMTEN text COLLATE utf8_unicode_ci NOT NULL,
  INCTEN int(3) NOT NULL,
  CONSTRAINT PK_TEN PRIMARY KEY(IDETEN)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE INC (
  RIEINC int(5) NOT NULL,
  TENINC int(3) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
ALTER TABLE `INC`
  ADD PRIMARY KEY (`RIEINC`),
  ADD KEY `FK_INC` (`RIEINC`),
  ADD KEY `FK1_INC`(`TENINC`);
ALTER TABLE `INC`
  ADD CONSTRAINT `INC_IBFK_1` FOREIGN KEY (`RIEINC`) REFERENCES `RIE` (`IDERIE`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `INC_IBFK_2` FOREIGN KEY (`TENINC`) REFERENCES `TEN` (`IDETEN`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;